dist: xenial
language: python
cache: pip

python:
  # Available Python (PyPy) can be listed by:
  #
  #   $ aws s3 ls s3://travis-python-archives/binaries/ubuntu/16.04/x86_64/
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"

matrix:
  include:
    - name: Black
      language: python
      python: 3.8
      install:
        - pip install black
      script:
        - black --check --diff .

    - name: 32bit build
      language: python
      services:
        - docker
      env:
        - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
      install:
        - pip install -U pip
        - pip install -r requirements.txt
        - make cython
        - docker pull $DOCKER_IMAGE
      script:
        - docker run --rm -v `pwd`:/io -w /io $DOCKER_IMAGE /io/docker/runtests.sh
    - name: "pypy2.7"
      python: "pypy2.7-7.1.1"
      install:
        - pip install -e .
      script:
        - py.test -v test
    - name: "pypy3"
      python: "pypy3.6-7.1.1"
      install:
        - pip install -e .
      script:
        - pytest -v test
    - name: "Python 2 (fallback)"
      python: "2.7"
      install:
        - pip install -U pip
        - pip install -U pytest pytest-cov codecov
        - pip install .
      script:
        - pytest -v test

install:
  - pip install -U pip
  - pip install -U pytest pytest-cov codecov
  - pip install -r requirements.txt
  - make cython
  - pip install -e .

script:
  - python -c 'import sys; print(hex(sys.maxsize))'
  - python -c 'from msgpack import _cmsgpack'
  - pytest -v test
  - MSGPACK_PUREPYTHON=x pytest -v test

after_success:
  - if [ -f .coverage ]; then
      codecov
    fi

# vim: sw=2 ts=2
