sudo: false
language: python
cache: pip

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

matrix:
  include:
    - sudo: required
      language: python
      services:
        - docker
      env:
        - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
      install:
        - pip install -U pip
        - pip install cython
        - cython --cplus msgpack/_packer.pyx msgpack/_unpacker.pyx
        - docker pull $DOCKER_IMAGE
      script:
        - docker run --rm -v `pwd`:/io -w /io $DOCKER_IMAGE /io/docker/runtests.sh
    - python: "pypy"
      install:
        - pip install -e .
      script:
        - py.test -v test


install:
  - pip install -U pip
  - pip install cython
  - cython --cplus msgpack/_packer.pyx msgpack/_unpacker.pyx
  - pip install -e .

script:
  - python -c 'import sys; print(hex(sys.maxsize))'
  - python -c 'from msgpack import _packer, _unpacker'
  - py.test -v test
  - MSGPACK_PUREPYTHON=x py.test -v test

# vim: sw=2 ts=2
