version: ~> 1.0
dist: xenial
language: python
cache: pip
arch:
   - arm64

python:
  # Available Python (PyPy) can be listed by:
  #
  #   $ aws s3 ls s3://travis-python-archives/binaries/ubuntu/16.04/x86_64/
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"

_pure: &pure
  install:
    - pip install -U pip
    - pip install -U pytest pytest-cov codecov hypothesis
    - pip install .
  script:
    - pytest --cov=msgpack -v test

matrix:
  include:
    - name: 32bit build
      arch: amd64
      language: python
      services:
        - docker
      env:
        - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
      install:
        - pip install -U pip
        - pip install -U hypothesis
        - pip install -r requirements.txt
        - make cython
        - docker pull $DOCKER_IMAGE
      script:
        - docker run --rm -v `pwd`:/io -w /io $DOCKER_IMAGE /io/docker/runtests.sh

    - arch: arm64
      name: arm64 32bit build
      language: python
      services:
        - docker
      env:
        - DOCKER_IMAGE=quay.io/pypa/manylinux2014_aarch64
      install:
        - pip install -U pip
        - pip install -U hypothesis
        - pip install -r requirements.txt
        - make cython
        - docker pull $DOCKER_IMAGE
      script:
        - docker run --rm -v `pwd`:/io -w /io $DOCKER_IMAGE /io/docker/runtests.sh

    - name: "Python 2 (fallback)"
      python: "2.7"
      <<: *pure

    - name: "pypy2.7"
      arch: amd64
      python: "pypy2.7-7.1.1"
      <<: *pure

    - name: "pypy3"
      arch: amd64
      python: "pypy3.6-7.1.1"
      <<: *pure

install:
  - pip install -U pip
  - pip install -U pytest pytest-cov codecov hypothesis
  - pip install -r requirements.txt  # Cython
  - make cython
  - pip install -e .

script:
  - python -c 'import sys; print(hex(sys.maxsize))'
  - python -c 'from msgpack import _cmsgpack'
  - pytest --cov=msgpack -v test
  - MSGPACK_PUREPYTHON=x pytest --cov=msgpack -v test

after_success:
  - if [ -f .coverage ]; then
      codecov;
    fi

# vim: sw=2 ts=2
