name: Black

on: ["push", "pull_request"]

jobs:
  black:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Checkout
        uses: actions/checkout@v1

      - name: Black Code Formatter
        run: |
          pip install black
          black --diff --check msgpack/ test/ setup.py
