name: Build macOS Wheels
on:
  push:
    branches:
      - main
  create:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Cythonize
        run: |
          pip install -U pip
          pip install -r requirements.txt
          make cython

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.2.2
        env:
          CIBW_ARCHS_MACOS: x86_64 universal2
          CIBW_SKIP: pp*

      - name: Run test
        run: |
          ls wheelhouse/
          pip install pytest
          pip install -v msgpack --only-binary :all: -f wheelhouse/ --no-index
          pytest -v test

      # Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Run test
        run: |
          pip install pytest
          pip install -v msgpack --only-binary :all: -f wheelhouse/ --no-index
          pytest -v test

      # Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Run test
        run: |
          pip install pytest
          pip install -v msgpack --only-binary :all: -f wheelhouse/ --no-index
          pytest -v test

      # Python 3.7
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Run test
        run: |
          pip install pytest
          pip install -v msgpack --only-binary :all: -f wheelhouse/ --no-index
          pytest -v test


      - name: Upload Wheels
        uses: actions/upload-artifact@v1
        with:
          name: macos-wheels
          path: ./wheelhouse/
